[tool.poetry]
name = "open-mcp-client"
version = "0.0.1"
description = "MCP Client"
authors = ["Ton Nom <ton.email@example.com>"]
license = "MIT"
packages = [
  { include = "open_mcp_client" }
]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
uvicorn = "^0.21.1"
fastapi = "^0.95.0"
langchain = "^0langchain = "^0.1.17"
"
openai = "^1.51.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
