services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: DB_TYPE
        value: sqlite
      - key: N8N_HOST
        value: n8n-d0ye.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: N8N_AUTH_MODE
        value: basic
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: kailee83400
      - key: N8N_BASIC_AUTH_PASSWORD
        value: kailee83400
      - key: N8N_USER_MANAGEMENT_DISABLED
        value: "true"
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-d0ye.onrender.com
